server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/search_engine
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
logging:
  level:
    root: INFO
    org.springframework.transaction: WARN
#    searchengine.services.implementation: DEBUG
#    org.hibernate.SQL: DEBUG
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 7
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  logback:
    rollingpolicy:
      file-name-pattern: logs/application-%d{yyyy-MM-dd}.%i.log
    appender:
      - name: FILE_DEBUG
        file: logs/debug.log
        pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
        level: DEBUG
        max-size: 10MB
      - name: FILE_ERROR
        file: logs/error.log
        pattern: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
        level: ERROR
        max-size: 10MB


# example values

indexing-settings:
  sites:
    - url: https://lenta.ru
      name: Лента.ру
    - url: https://skillbox.ru
      name: Skillbox
    - url: https://playback.ru
      name: PlayBack.Ru
    - url: https://metanit.com
      name: METANIT.COM